const HTTPS_PROTOCOL="https:/"

const HTTP_PROTOCOL="http:/"

const BASE_URL = "/wetap.in/2022"

const SUB_URL="/assetSearch"

const OTP_LOGIN_URL = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/otp_login`

const OTP_VERIFICATION_URL = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/otp_verification`

const USER_REGISTER=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/user_registration`

const SEARCH_URL = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/search`

const COUNTRIES_LIST=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/countries_list`

const CITIES_LIST = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/cities_list`

const STATES_LIST = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/states_list`

const SEARCH_DETAILS = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/search_details`

const SUBMIT_ORDER = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/submit_order`

const GET_PROFILE = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/get_profile`

const UPDATE_PROFILE = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/update_profile`

const MANAGE_NOMINEES = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/manage_nominees`

const MANAGE_LEGAL_HEIRS = `${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/manage_legal_heirs`

const USER_ORDER=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/user_order`

const GET_USER_LEGAL_HEIRS=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/get_user_legal_heirs`

const GET_USER_NOMINEES=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/get_user_nominees`

const REQUEST_FOR_CONSULTANT=`${HTTPS_PROTOCOL}${BASE_URL}${SUB_URL}/request_for_consultant`

module.exports = {
    BASE_URL, OTP_LOGIN_URL, OTP_VERIFICATION_URL, SEARCH_URL, CITIES_LIST, STATES_LIST, SEARCH_DETAILS, SUBMIT_ORDER, GET_PROFILE, UPDATE_PROFILE, MANAGE_NOMINEES,
    MANAGE_LEGAL_HEIRS,USER_ORDER,USER_REGISTER,GET_USER_LEGAL_HEIRS,GET_USER_NOMINEES,REQUEST_FOR_CONSULTANT,COUNTRIES_LIST
}
